---
message_bus_servers:
  - host: 10.244.0.6:4222
    user: nats
    password: nats
external_host: some-external-host
external_ip: 127.0.0.1
port: 8080
health_checker:
  name: some-healthcheckable-cluster
  interval_in_seconds: 10
